_commit: v1.6.0
_src_path: gh:superlinear-ai/substrate
author_email: itavfx04@gmail.com
author_name: Francesco Idato
project_description: Content aware AI agent based on local running models (LMstudio)
project_name: fluxa
project_type: package
project_url: https://github.com/devfrx/fluxa.git
python_version: '3.10'
typing: optional
with_conventional_commits: false
with_typer_cli: true
